// SPDX-License-Identifier: AGPL-3.0-only
package tech.g24.feresaslicer.slicer

import java.io.BufferedOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.nio.charset.StandardCharsets
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.util.Base64
import java.util.Locale

internal data class GcodeThumbnail(
    val width: Int,
    val height: Int,
    val png: ByteArray,
) {
    init {
        require(width in 1..999 && height in 1..999) {
            "G-code thumbnail dimensions must be between 1 and 999 pixels"
        }
        require(png.startsWith(PngSignature)) { "G-code thumbnail must be a PNG image" }
    }
}

internal data class FeresaGcodeMetadata(
    val applicationVersion: String,
    /** Must use Orca/Prusa's `yyyy-MM-dd at HH:mm:ss` header timestamp shape. */
    val generatedAt: String,
    val engineName: String,
    val engineRevision: String,
    val modelNames: List<String>,
    val printerProfileName: String?,
    val processProfileName: String?,
    val filamentProfileName: String?,
    val nativeSettings: Map<String, String>,
    val report: SliceReport,
)

/**
 * Adds Feresa ownership, Orca/Prusa-compatible thumbnails and standard metadata to plain G-code.
 *
 * The block shape intentionally follows OrcaSlicer
 * `src/libslic3r/GCode/Thumbnails.hpp` at pinned commit
 * `d5dbd96dd64b830076c81053ed5fda26d5a1771b`: PNG bytes are Base64 encoded, wrapped at 78
 * characters and enclosed by `thumbnail begin` / `thumbnail end`. The native mobile JNI is
 * invoked with a null desktop thumbnail callback, so adapting the output format here is the
 * smallest Android-suitable path.
 *
 * Existing G/M commands are streamed byte-for-byte between a comment-only header and footer. A
 * sibling temporary file is synced and atomically moved over the source whenever the filesystem
 * supports it, so a failed enhancement cannot leave a partially written printable file.
 */
internal object FeresaGcodePostProcessor {
    fun enhance(
        gcode: File,
        thumbnails: List<GcodeThumbnail>,
        metadata: FeresaGcodeMetadata,
    ) {
        require(gcode.isFile && gcode.length() > 0L) { "G-code file is missing or empty: $gcode" }
        require(metadata.applicationVersion.isNotBlank()) { "Feresa version must not be blank" }
        require(metadata.generatedAt.matches(OrcaTimestamp)) {
            "Feresa G-code timestamp must use yyyy-MM-dd at HH:mm:ss"
        }

        val orderedThumbnails = thumbnails
            .distinctBy { it.width to it.height }
            .sortedBy { it.width.toLong() * it.height }
        val header = buildHeader(orderedThumbnails, metadata)
        val footer = buildFooter(metadata)
        val parent = requireNotNull(gcode.absoluteFile.parentFile) {
            "Cannot resolve G-code parent directory"
        }
        require(parent.isDirectory || parent.mkdirs()) { "Cannot create G-code directory: $parent" }
        val temporary = File.createTempFile(".${gcode.name}.feresa-", ".tmp", parent)

        try {
            FileOutputStream(temporary).use { fileOutput ->
                val output = BufferedOutputStream(fileOutput)
                try {
                    output.write(header.toByteArray(StandardCharsets.UTF_8))
                    FileInputStream(gcode).use { input -> input.copyTo(output) }
                    output.write('\n'.code)
                    output.write(footer.toByteArray(StandardCharsets.UTF_8))
                    output.flush()
                    fileOutput.fd.sync()
                } finally {
                    output.close()
                }
            }
            replaceAtomicallyWhenSupported(temporary, gcode)
        } finally {
            if (temporary.exists()) temporary.delete()
        }
    }

    private fun buildHeader(
        thumbnails: List<GcodeThumbnail>,
        metadata: FeresaGcodeMetadata,
    ): String = buildString {
        append("; generated by Feresa Slicer ")
            .append(safeCommentValue(metadata.applicationVersion))
            .append(" on ")
            .append(metadata.generatedAt)
            .append('\n')
        append("; slicing engine = ")
            .append(safeCommentValue(metadata.engineName))
            .append(' ')
            .append(safeCommentValue(metadata.engineRevision))
            .append('\n')
        append("; source models = ")
            .append(safeCommentValue(metadata.modelNames.joinToString(", ")))
            .append("\n\n")
        thumbnails.forEach { thumbnail -> appendThumbnail(thumbnail) }
    }

    private fun StringBuilder.appendThumbnail(thumbnail: GcodeThumbnail) {
        val encoded = Base64.getEncoder().encodeToString(thumbnail.png)
        append("; THUMBNAIL_BLOCK_START\n")
        append(";\n")
        append("; thumbnail begin ")
            .append(thumbnail.width)
            .append('x')
            .append(thumbnail.height)
            .append(' ')
            .append(encoded.length)
            .append('\n')
        encoded.chunked(ThumbnailBase64RowLength).forEach { row ->
            append("; ").append(row).append('\n')
        }
        append("; thumbnail end\n")
        append("; THUMBNAIL_BLOCK_END\n\n")
    }

    private fun buildFooter(metadata: FeresaGcodeMetadata): String = buildString {
        append("; FERESA_METADATA_BLOCK_START\n")
        appendMetadata("feresa_slicer_version", metadata.applicationVersion)
        appendMetadata("feresa_slicing_engine", metadata.engineName)
        appendMetadata("feresa_slicing_engine_revision", metadata.engineRevision)
        appendMetadata("model_name", metadata.modelNames.joinToString(", "))
        metadata.printerProfileName?.let { appendMetadata("printer_settings_id", it) }
        metadata.processProfileName?.let { appendMetadata("print_settings_id", it) }
        metadata.filamentProfileName?.let { appendMetadata("filament_settings_id", it) }

        appendSetting(metadata, outputKey = "filament_type", nativeKey = "filament_type")
        appendSetting(metadata, outputKey = "nozzle_diameter", nativeKey = "nozzle_diameter")
        appendSetting(metadata, outputKey = "layer_height", nativeKey = "layer_height")
        appendSetting(
            metadata,
            outputKey = "first_layer_height",
            nativeKey = "initial_layer_print_height",
        )
        appendSetting(
            metadata,
            outputKey = "first_layer_temperature",
            nativeKey = "nozzle_temperature_initial_layer",
        )
        appendSetting(
            metadata,
            outputKey = "first_layer_bed_temperature",
            nativeKey = "hot_plate_temp_initial_layer",
        )

        append("; filament used [mm] = ")
            .append(decimal(metadata.report.filamentLengthMm, 2))
            .append('\n')
        append("; filament used [g] = ")
            .append(decimal(metadata.report.filamentWeightGrams, 2))
            .append('\n')
        append("; total filament used [g] = ")
            .append(decimal(metadata.report.filamentWeightGrams, 2))
            .append('\n')
        append("; estimated printing time (normal mode) = ")
            .append(formatDuration(metadata.report.estimatedPrintTimeSeconds))
            .append('\n')
        append("; total layers count = ")
            .append(metadata.report.layers.coerceAtLeast(0L))
            .append('\n')
        append("; max_z_height = ")
            .append(decimal(metadata.report.maximumZmm, 3))
            .append('\n')
        append("; FERESA_METADATA_BLOCK_END\n")
    }

    private fun StringBuilder.appendSetting(
        metadata: FeresaGcodeMetadata,
        outputKey: String,
        nativeKey: String,
    ) {
        metadata.nativeSettings[nativeKey]
            ?.substringBefore(',')
            ?.trim()
            ?.trim('"')
            ?.takeIf(String::isNotBlank)
            ?.let { appendMetadata(outputKey, it) }
    }

    private fun StringBuilder.appendMetadata(key: String, value: String) {
        append("; ").append(key).append(" = ").append(safeCommentValue(value)).append('\n')
    }

    private fun formatDuration(totalSeconds: Long): String {
        var remaining = totalSeconds.coerceAtLeast(0L)
        val days = remaining / 86_400L
        remaining %= 86_400L
        val hours = remaining / 3_600L
        remaining %= 3_600L
        val minutes = remaining / 60L
        val seconds = remaining % 60L
        return buildList {
            if (days > 0L) add("${days}d")
            if (hours > 0L) add("${hours}h")
            if (minutes > 0L) add("${minutes}m")
            if (seconds > 0L || isEmpty()) add("${seconds}s")
        }.joinToString(" ")
    }

    private fun decimal(value: Double, digits: Int): String =
        String.format(Locale.US, "%.${digits}f", value.takeIf(Double::isFinite) ?: 0.0)

    private fun safeCommentValue(value: String): String = buildString {
        value.take(MaximumMetadataValueLength).forEach { character ->
            when {
                character == '\r' || character == '\n' || character == '\u0000' -> append(' ')
                character.isISOControl() -> append(' ')
                else -> append(character)
            }
        }
    }.trim().ifEmpty { "unknown" }

    private fun replaceAtomicallyWhenSupported(temporary: File, destination: File) {
        try {
            Files.move(
                temporary.toPath(),
                destination.toPath(),
                StandardCopyOption.ATOMIC_MOVE,
                StandardCopyOption.REPLACE_EXISTING,
            )
        } catch (_: AtomicMoveNotSupportedException) {
            Files.move(
                temporary.toPath(),
                destination.toPath(),
                StandardCopyOption.REPLACE_EXISTING,
            )
        } catch (_: UnsupportedOperationException) {
            Files.move(
                temporary.toPath(),
                destination.toPath(),
                StandardCopyOption.REPLACE_EXISTING,
            )
        }
    }
}

private fun ByteArray.startsWith(prefix: ByteArray): Boolean =
    size >= prefix.size && prefix.indices.all { index -> this[index] == prefix[index] }

private val PngSignature = byteArrayOf(
    0x89.toByte(), 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
)
private val OrcaTimestamp = Regex("\\d{4}-\\d{2}-\\d{2} at \\d{2}:\\d{2}:\\d{2}")
private const val ThumbnailBase64RowLength = 78
private const val MaximumMetadataValueLength = 512
