// SPDX-License-Identifier: AGPL-3.0-only
package tech.g24.feresaslicer.slicer

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Base64
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

class FeresaGcodePostProcessorTest {
    @Test
    fun `writes Orca thumbnail blocks and keeps native commands byte identical`() {
        val directory = Files.createTempDirectory("feresa-gcode-preview").toFile()
        val gcode = directory.resolve("model.gcode")
        val original = (
            "; generated by OrcaSlicer 2.5.0 on 2026-08-26 at 10:00:00\r\n" +
                "G90\r\nM82\r\nG1 X1.250 Y2.500 E0.100 F1200\r\n"
            ).toByteArray(StandardCharsets.US_ASCII)
        gcode.writeBytes(original)
        val png = Base64.getDecoder().decode(OnePixelPngBase64)

        FeresaGcodePostProcessor.enhance(
            gcode = gcode,
            thumbnails = listOf(
                GcodeThumbnail(300, 300, png),
                GcodeThumbnail(32, 32, png),
            ),
            metadata = metadata(
                modelNames = listOf("basket\nG28\r;unsafe"),
                report = SliceReport(
                    success = true,
                    message = "G-code created",
                    layers = 42,
                    filamentLengthMm = 1_234.567,
                    estimatedPrintTimeSeconds = 3_723,
                    filamentWeightGrams = 3.14159,
                    maximumZmm = 8.7654,
                ),
            ),
        )

        val enhanced = gcode.readBytes()
        val originalOffset = enhanced.indexOf(original)
        assertTrue("Original G-code bytes were not retained", originalOffset >= 0)
        assertArrayEquals(
            original,
            enhanced.copyOfRange(originalOffset, originalOffset + original.size),
        )
        assertEquals(commandLines(original), commandLines(enhanced))

        val text = enhanced.toString(StandardCharsets.UTF_8)
        assertTrue(
            text.startsWith(
                "; generated by Feresa Slicer 0.16.0-test on 2026-08-26 at 12:34:56\n",
            ),
        )
        assertTrue(text.contains("; slicing engine = OrcaSlicer Mobile 6fc2e14"))
        assertEquals(2, ThumbnailHeader.findAll(text).count())
        assertTrue(text.indexOf("thumbnail begin 32x32") < text.indexOf("thumbnail begin 300x300"))

        ThumbnailBlock.findAll(text).forEach { match ->
            val declaredLength = match.groupValues[3].toInt()
            val rows = match.groupValues[4]
                .lineSequence()
                .filter(String::isNotBlank)
                .map { it.removePrefix("; ") }
                .toList()
            assertTrue(rows.all { it.length <= 78 })
            val encoded = rows.joinToString("")
            assertEquals(declaredLength, encoded.length)
            assertArrayEquals(png, Base64.getDecoder().decode(encoded))
        }

        assertFalse("A model name injected executable G-code", text.contains("\nG28\n"))
        assertTrue(text.contains("; filament used [mm] = 1234.57"))
        assertTrue(text.contains("; total filament used [g] = 3.14"))
        assertTrue(text.contains("; estimated printing time (normal mode) = 1h 2m 3s"))
        assertTrue(text.contains("; total layers count = 42"))
        assertTrue(text.contains("; max_z_height = 8.765"))
        assertTrue(text.contains("; filament_type = PLA"))
        assertTrue(text.contains("; nozzle_diameter = 0.4"))
        assertTrue(text.endsWith("; FERESA_METADATA_BLOCK_END\n"))
    }

    @Test
    fun `invalid metadata fails before replacing printable file`() {
        val gcode = Files.createTempFile("feresa-gcode-invalid", ".gcode").toFile()
        val original = "G28\nM84\n".toByteArray(StandardCharsets.US_ASCII)
        gcode.writeBytes(original)

        val failure = runCatching {
            FeresaGcodePostProcessor.enhance(
                gcode = gcode,
                thumbnails = emptyList(),
                metadata = metadata().copy(generatedAt = "not-a-timestamp"),
            )
        }.exceptionOrNull()

        assertNotNull(failure)
        assertArrayEquals(original, gcode.readBytes())
    }

    @Test
    fun `toolpath reader includes only positive extrusion moves across coordinate modes`() {
        val gcode = Files.createTempFile("feresa-toolpath", ".gcode").toFile().apply {
            writeText(
                """
                G90
                M83
                G0 X10 Y5 Z0.2
                G1 X20 Y5 E1.0
                G1 E-0.4
                G1 X30 Y5 E0.5
                G92 E0
                M82
                G1 X40 Y5 E1.0
                G1 X50 Y5 E0.5
                G91
                M83
                G1 X5 Y5 Z0.2 E0.2
                """.trimIndent(),
            )
        }
        val segments = mutableListOf<ExtrusionToolpathSegment>()

        forEachExtrusionToolpathSegment(gcode, segments::add)

        assertEquals(4, segments.size)
        assertEquals(ToolpathPoint3d(10.0, 5.0, 0.2), segments[0].start)
        assertEquals(ToolpathPoint3d(20.0, 5.0, 0.2), segments[0].end)
        assertEquals(ToolpathPoint3d(50.0, 5.0, 0.2), segments[3].start)
        assertEquals(ToolpathPoint3d(55.0, 10.0, 0.4), segments[3].end)
        assertEquals(4L, scanIsometricToolpathBounds(gcode)?.segmentCount)
    }

    private fun metadata(
        modelNames: List<String> = listOf("model"),
        report: SliceReport = SliceReport(success = true, message = "G-code created"),
    ): FeresaGcodeMetadata = FeresaGcodeMetadata(
        applicationVersion = "0.16.0-test",
        generatedAt = "2026-08-26 at 12:34:56",
        engineName = "OrcaSlicer Mobile",
        engineRevision = "6fc2e14",
        modelNames = modelNames,
        printerProfileName = "Generic Klipper",
        processProfileName = "0.20 mm Standard",
        filamentProfileName = "Generic PLA",
        nativeSettings = mapOf(
            "filament_type" to "PLA",
            "nozzle_diameter" to "0.4",
            "layer_height" to "0.2",
            "initial_layer_print_height" to "0.25",
            "nozzle_temperature_initial_layer" to "215",
            "hot_plate_temp_initial_layer" to "60",
        ),
        report = report,
    )

    private fun commandLines(gcode: ByteArray): List<String> =
        gcode.toString(StandardCharsets.US_ASCII)
            .lineSequence()
            .filter { line -> line.startsWith('G') || line.startsWith('M') }
            .toList()

    private fun ByteArray.indexOf(needle: ByteArray): Int {
        if (needle.isEmpty()) return 0
        for (start in 0..size - needle.size) {
            if (needle.indices.all { offset -> this[start + offset] == needle[offset] }) return start
        }
        return -1
    }
}

private val ThumbnailHeader = Regex("; thumbnail begin (\\d+)x(\\d+) (\\d+)")
private val ThumbnailBlock = Regex(
    "; thumbnail begin (\\d+)x(\\d+) (\\d+)\\n((?:; [A-Za-z0-9+/=]+\\n)+); thumbnail end",
)
private const val OnePixelPngBase64 =
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
