// SPDX-License-Identifier: AGPL-3.0-only
package tech.g24.feresaslicer.ui

import tech.g24.feresaslicer.slicer.OrcaProcessSettingsPayload

/** Converts every process control currently exposed by Feresa to its OrcaSlicer wire key. */
fun PrintSettingsState.toOrcaProcessSettingsPayload(): OrcaProcessSettingsPayload =
    OrcaProcessSettingsPayload.builder()
        .put("layer_height", layerHeight.orcaScalar())
        .put("initial_layer_print_height", initialLayerHeight.orcaScalar())
        .put("line_width", lineWidth.orcaScalar())
        .put("initial_layer_line_width", initialLayerLineWidth.orcaScalar())
        .put("outer_wall_line_width", outerWallLineWidth.orcaScalar())
        .put("seam_position", seamPosition)
        .put("seam_gap", seamGap.orcaPercent())
        .put("staggered_inner_seams", staggeredInnerSeams.orcaFlag())
        .put("resolution", resolution.orcaScalar())
        .put("enable_arc_fitting", arcFitting.orcaFlag())
        .put("precise_outer_wall", preciseOuterWall.orcaFlag())
        .put("xy_hole_compensation", xyHoleCompensation.orcaScalar())
        .put("elefant_foot_compensation", elephantFootCompensation.orcaScalar())
        .put("wall_generator", wallGenerator)
        .put("wall_sequence", wallSequence)
        .put("is_infill_first", infillFirst.orcaFlag())
        .put("only_one_wall_top", onlyOneWallTop.orcaFlag())
        .put("detect_overhang_wall", detectOverhangWall.orcaFlag())
        .put("bridge_flow", bridgeFlow.orcaScalar())
        .put("wall_loops", wallLoops.orcaScalar())
        .put("alternate_extra_wall", alternateExtraWall.orcaFlag())
        .put("detect_thin_wall", detectThinWall.orcaFlag())
        .put("top_shell_layers", topShellLayers.orcaScalar())
        .put("bottom_shell_layers", bottomShellLayers.orcaScalar())
        .put("top_surface_pattern", topSurfacePattern)
        .put("bottom_surface_pattern", bottomSurfacePattern)
        .put("sparse_infill_density", infillDensity.orcaPercent())
        .put("sparse_infill_pattern", infillPattern)
        .put("infill_direction", infillDirection.orcaScalar())
        .put("infill_wall_overlap", infillWallOverlap.orcaPercent())
        .put("enable_support", enableSupport.orcaFlag())
        .put("support_type", supportType)
        .put("support_threshold_angle", supportThresholdAngle.orcaScalar())
        .put("support_on_build_plate_only", supportOnBuildPlateOnly.orcaFlag())
        .put("raft_layers", raftLayers.orcaScalar())
        .put("support_top_z_distance", supportTopDistance.orcaScalar())
        .put("support_bottom_z_distance", supportBottomDistance.orcaScalar())
        .put("support_interface_top_layers", supportInterfaceTopLayers.orcaScalar())
        .put("support_interface_bottom_layers", supportInterfaceBottomLayers.orcaScalar())
        .put("support_interface_spacing", supportInterfaceSpacing.orcaScalar())
        .put("tree_support_tip_diameter", treeTipDiameter.orcaScalar())
        .put("tree_support_branch_distance", treeBranchDistance.orcaScalar())
        .put("tree_support_branch_angle", treeBranchAngle.orcaScalar())
        .put("enable_prime_tower", enablePrimeTower.orcaFlag())
        .put("prime_tower_width", primeTowerWidth.orcaScalar())
        .put("prime_volume", primeVolume.orcaScalar())
        .put("prime_tower_brim_width", primeTowerBrimWidth.orcaScalar())
        .put("flush_into_infill", flushIntoInfill.orcaFlag())
        .put("flush_into_support", flushIntoSupport.orcaFlag())
        .put("ooze_prevention", oozePrevention.orcaFlag())
        .put("standby_temperature_delta", standbyTemperatureDelta.orcaScalar())
        .put("outer_wall_filament_id", outerWallFilament.orcaScalar())
        .put("sparse_infill_filament_id", infillFilament.orcaScalar())
        .put("skirt_loops", skirtLoops.orcaScalar())
        .put("skirt_distance", skirtDistance.orcaScalar())
        .put("min_skirt_length", minSkirtLength.orcaScalar())
        .put("brim_type", brimType)
        .put("brim_width", brimWidth.orcaScalar())
        .put("brim_object_gap", brimObjectGap.orcaScalar())
        // Orca has no generic process "print_speed" option. The corresponding UI value is the
        // explicit outer-wall speed, while printSpeed remains a legacy summary field.
        .put("outer_wall_speed", outerWallSpeed.orcaScalar())
        .put("inner_wall_speed", innerWallSpeed.orcaScalar())
        .put("sparse_infill_speed", infillSpeed.orcaScalar())
        .put("travel_speed", travelSpeed.orcaScalar())
        .put("default_acceleration", acceleration.orcaScalar())
        .put("slicing_mode", slicingMode)
        .put("print_sequence", printSequence)
        .put("spiral_mode", spiralMode.orcaFlag())
        .put("fuzzy_skin", fuzzySkin)
        .put("gcode_comments", gcodeComments.orcaFlag())
        .put("gcode_label_objects", labelObjects.orcaFlag())
        .put("exclude_object", excludeObjects.orcaFlag())
        .put("filename_format", filenameFormat)
        .build()

private fun Boolean.orcaFlag(): String = if (this) "1" else "0"

private fun String.orcaScalar(): String = trim()

private fun String.orcaPercent(): String = "${trim().removeSuffix("%").trim()}%"
