// SPDX-License-Identifier: AGPL-3.0-only
package tech.g24.feresaslicer.ui

import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.Text as MaterialText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit
import java.util.Locale

enum class UiLanguage {
    RUSSIAN,
    ENGLISH,
}

/** Explicit in-app language. Feresa defaults to Russian until the user changes it. */
val LocalUiLanguage = staticCompositionLocalOf { UiLanguage.RUSSIAN }

fun resolveUiLanguage(locale: Locale): UiLanguage =
    if (locale.language.equals("ru", ignoreCase = true)) UiLanguage.RUSSIAN else UiLanguage.ENGLISH

@Composable
fun currentUiLanguage(): UiLanguage = LocalUiLanguage.current

/**
 * Localized Material 3 text used throughout the app.
 *
 * The project originally shipped with Russian literals embedded in Compose code. Keeping this
 * compatibility layer lets every existing screen participate in locale changes while translations
 * are centralized and testable. The language is selected explicitly in the app settings and
 * defaults to Russian on the first launch.
 */
@Composable
fun Text(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: (TextLayoutResult) -> Unit = {},
    style: TextStyle = LocalTextStyle.current,
) {
    MaterialText(
        text = localizeUiText(text, currentUiLanguage()),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style,
    )
}

fun localizeUiText(text: String, language: UiLanguage): String {
    if (language == UiLanguage.RUSSIAN || text.none { it in '\u0400'..'\u04FF' }) return text
    ENGLISH_TEXT[text]?.let { return it }

    var translated = text
    ENGLISH_REPLACEMENTS.forEach { (russian, english) ->
        translated = translated.replace(russian, english)
    }
    return translated
}

private val ENGLISH_TEXT = mapOf(
    // Application shell and model workspace.
    "Системная" to "System",
    "Светлая" to "Light",
    "Тёмная" to "Dark",
    "Модель" to "Model",
    "Модель и печатный стол" to "Model and print bed",
    "Принтер" to "Printer",
    "Профиль принтера" to "Printer profile",
    "Филамент" to "Filament",
    "Профиль материала" to "Material profile",
    "Печать" to "Print",
    "Параметры печати" to "Print settings",
    "Приложение" to "App",
    "Настройки и синхронизация" to "Settings and synchronization",
    "Меню" to "Menu",
    "Файл" to "File",
    "Вид" to "View",
    "Положение" to "Position",
    "Нарезка" to "Slice",
    "Файл модели" to "Model file",
    "Модели на столе" to "Models on the plate",
    "Файл не выбран" to "No file selected",
    "Поддерживаются модели STL в binary- и ASCII-формате." to "Binary and ASCII STL models are supported.",
    "Поддерживаются STL, OBJ и 3MF. Можно выбрать несколько файлов сразу." to
        "STL, OBJ, and 3MF are supported. You can select multiple files at once.",
    "Формат: STL" to "Format: STL",
    "Состояние: нарезка готова" to "Status: slicing complete",
    "Состояние: модель загружена" to "Status: model loaded",
    "Загрузить STL" to "Load STL",
    "Добавить STL" to "Add STL",
    "Загрузить модель" to "Load model",
    "Добавить модель" to "Add model",
    "Удалить выбранную модель" to "Remove selected model",
    "Заменить STL" to "Replace STL",
    "Удалить файл" to "Remove file",
    "Расположение модели" to "Model placement",
    "Создание 3D-модели по фото пока недоступно" to "Creating a 3D model from a photo is not available yet",
    "Экспорт профилей будет добавлен в следующей версии" to "Profile export will be added in a future version",
    "Модель выходит за пределы печатного стола" to "The model extends beyond the print bed",
    "Позиция X" to "X position",
    "Позиция Y" to "Y position",
    "Позиция Z" to "Z position",
    "Положение XYZ" to "XYZ position",
    "Поворот" to "Rotation",
    "Поворот XYZ" to "XYZ rotation",
    "Поворот X" to "X rotation",
    "Поворот Y" to "Y rotation",
    "Поворот Z" to "Z rotation",
    "Масштаб" to "Scale",
    "Масштаб X" to "X scale",
    "Масштаб Y" to "Y scale",
    "Масштаб Z" to "Z scale",
    "Сохранять пропорции" to "Keep proportions",
    "По центру" to "Center",
    "На стол" to "Place on bed",
    "Повернуть 90°" to "Rotate 90°",
    "Повернуть Z 90°" to "Rotate Z 90°",
    "Положить гранью" to "Lay flat",
    "Дублировать" to "Duplicate",
    "Переименовать" to "Rename",
    "Переименовать модель" to "Rename model",
    "Название" to "Name",
    "Автоматически расставить" to "Auto arrange",
    "Расставить" to "Arrange",
    "Автоориент." to "Auto orient",
    "Автоориент. (бета)" to "Auto orient (beta)",
    "Позиция" to "Position",
    "На грань" to "Lay flat",
    "Крупнейшей гранью" to "Largest face down",
    "В пределах стола" to "Within bed",
    "Вне стола" to "Outside bed",
    "Модель автоматически ориентирована" to "Model auto-oriented",
    "Не удалось ориентировать модель" to "Could not orient model",
    "Выберите модель на столе" to "Select a model on the plate",
    "Объект выходит за пределы области печати" to "The object is outside the build volume",
    "Модель размещена по центру" to "Model centered",
    "Модель опущена на стол" to "Model placed on bed",
    "Модель повёрнута на 90°" to "Model rotated by 90°",
    "Модель положена крупнейшей гранью" to "Model placed on its largest face",
    "Создана копия модели" to "Model duplicated",
    "Копия создана; не всё поместилось на стол" to "Duplicate created; not everything fit on the bed",
    "Модели автоматически расставлены" to "Models auto-arranged",
    "Модель переименована" to "Model renamed",
    "Модели" to "Models",
    "Удалить" to "Remove",
    "Из фото" to "From photo",
    "Калибр." to "Calibrate",
    "Импорт проф." to "Import profiles",
    "Экспорт проф." to "Export profiles",
    "Общий вид" to "Overview",
    "Траектория" to "Toolpath",
    "Масштаб 1:1" to "Scale 1:1",
    "Нарезать" to "Slice",
    "На печать" to "Send to printer",
    "Сохранить" to "Save",
    "НАРЕЗАТЬ МОДЕЛЬ" to "SLICE MODEL",
    "Нарезка…" to "Slicing…",
    "Нарезка модели…" to "Slicing model…",
    "Выберите STL во вкладке «Файл», затем вернитесь сюда для нарезки." to "Select an STL on the File tab, then return here to slice it.",
    "Модель готова. После нарезки здесь появится послойная траектория G-code." to "The model is ready. A layer-by-layer G-code toolpath will appear here after slicing.",
    "Модели готовы. После нарезки здесь появится послойная траектория G-code." to "The models are ready. A layer-by-layer G-code toolpath will appear here after slicing.",

    // App settings, accounts, and dialogs.
    "Настройки приложения" to "App settings",
    "Язык интерфейса" to "Interface language",
    "Русский" to "Russian",
    "Английский" to "English",
    "Тема" to "Theme",
    "Локальный слайсер" to "Local slicer",
    "Включён и всегда доступен без интернета" to "Enabled and always available offline",
    "Локальный слайсер бесплатный" to "Local slicing is free",
    "Синхронизация профилей OrcaCloud доступна после входа." to "OrcaCloud profile synchronization is available after sign-in.",
    "Свернуть список" to "Collapse list",
    "Синхронизация профилей" to "Profile synchronization",
    "Загружено из OrcaCloud" to "Loaded from OrcaCloud",
    "Подключение загружено из OrcaCloud" to "Connection loaded from OrcaCloud",
    "Показаны данные из локального кэша" to "Showing locally cached data",
    "После входа здесь появятся ваши профили OrcaCloud." to "Your OrcaCloud profiles will appear here after you sign in.",
    "Синхронизация…" to "Synchronizing…",
    "Обновить профили" to "Refresh profiles",
    "Только чтение: приложение загружает профили, но не изменяет данные OrcaCloud." to "Read-only: the app downloads profiles but does not modify OrcaCloud data.",
    "AGPL-3.0 · Лицензия и исходный код" to "AGPL-3.0 · License and source code",
    "Политика конфиденциальности" to "Privacy policy",
    "Открыть исходный код" to "Open source code",
    "Не удалось открыть политику конфиденциальности" to "Could not open the privacy policy",
    "Не удалось открыть исходный код" to "Could not open the source code",
    "Закрыть" to "Close",
    "Свободное программное обеспечение" to "Free and open-source software",
    "Feresa Slicer распространяется по лицензии GNU AGPL версии 3. Исходный код, сценарии сборки, уведомления и текст лицензии включены в проект. Программа предоставляется без гарантий." to
        "Feresa Slicer is distributed under the GNU AGPL version 3. The source code, build scripts, notices, and license text are included in the project. The software is provided without warranty.",
    "Учётная запись OrcaCloud" to "OrcaCloud account",
    "Проверка сохранённой сессии…" to "Checking saved session…",
    "Безопасный вход откроется в браузере. Приложение не получает ваш пароль." to "Secure sign-in opens in your browser. The app never receives your password.",
    "Отменить вход" to "Cancel sign-in",
    "Выйти" to "Sign out",
    "Управление и удаление аккаунта" to "Manage or delete account",
    "Не удалось открыть управление аккаунтом Orca Cloud" to "Could not open Orca Cloud account management",
    "Повторить" to "Retry",
    "Войти" to "Sign in",
    "Локальный demo для проверки Google Play" to "Local Google Play review demo",
    "Скрыть локальный demo Google Play" to "Hide local Google Play demo",
    "Вход открывает встроенные тестовые профили без подключения к OrcaCloud или принтеру." to
        "This sign-in opens bundled test profiles without connecting to OrcaCloud or a printer.",
    "Demo-логин" to "Demo username",
    "Demo-пароль" to "Demo password",
    "Открыть локальный demo" to "Open local demo",
    "Используются только встроенные тестовые профили. Сеть и реальные данные отключены." to
        "Only bundled test profiles are used. Network access and real data are disabled.",
    "Неверные данные локального demo Google Play." to "Incorrect local Google Play demo credentials.",
    "Тестовые профили встроены в приложение; сеть не используется." to
        "Test profiles are bundled with the app; no network is used.",
    "Demo не подключается к OrcaCloud, принтерам или пользовательским данным." to
        "The demo does not connect to OrcaCloud, printers, or user data.",
    "Локальные demo-профили" to "Local demo profiles",
    "Сбросить demo-профили" to "Reset demo profiles",
    "↻ Сбросить demo-профили" to "↻ Reset demo profiles",
    "Открыть меню приложения" to "Open app menu",
    "Обновить из OrcaCloud" to "Refresh from OrcaCloud",
    "Обновление…" to "Refreshing…",
    "В OrcaCloud нет пользовательских профилей этого типа." to "There are no custom profiles of this type in OrcaCloud.",
    "Войдите в OrcaCloud, чтобы загрузить свои профили." to "Sign in to OrcaCloud to load your profiles.",
    "Профили пока не загружены" to "Profiles have not been loaded yet",
    "Войти в OrcaCloud" to "Sign in to OrcaCloud",
    "Выбран" to "Selected",
    "Выбрать" to "Select",
    "Активен" to "Active",
    "Подключён" to "Connected",
    "Используется для подключения" to "Used for connection",

    // Printer, profiles, and catalog.
    "Подключение к принтеру" to "Printer connection",
    "Авторизация настроена" to "Authentication configured",
    "Без API-ключа" to "No API key",
    "Проверка…" to "Checking…",
    "Проверить подключение" to "Test connection",
    "Принтер не подключён" to "Printer not connected",
    "Подключение не установлено" to "Connection failed",
    "Принтер готов к запуску" to "Printer is ready to start",
    "Запуск сейчас недоступен" to "Start is currently unavailable",
    "Выберите профиль OrcaCloud, содержащий print_host и host_type." to "Select an OrcaCloud profile containing print_host and host_type.",
    "Добавьте адрес Moonraker или OctoPrint вручную либо выберите профиль OrcaCloud с подключением." to
        "Add a Moonraker or OctoPrint address manually, or select an OrcaCloud profile with a connection.",
    "Ручное подключение" to "Manual connection",
    "Профиль OrcaCloud" to "OrcaCloud profile",
    "Добавить вручную" to "Add manually",
    "Изменить вручную" to "Edit manually",
    "Использовать" to "Use",
    "Название принтера" to "Printer name",
    "IP-адрес или URL" to "IP address or URL",
    "Порт, если нестандартный" to "Port, if non-standard",
    "API-ключ, если нужен" to "API key, if required",
    "Логин" to "Username",
    "Пароль" to "Password",
    "HTTP не шифрует ключ и пароль. Используйте его только в доверенной локальной сети." to
        "HTTP does not encrypt the key or password. Use it only on a trusted local network.",
    "Сохранить" to "Save",
    "Удалить ручное подключение" to "Delete manual connection",
    "Ручное подключение сохранено" to "Manual connection saved",
    "Ручное подключение выбрано" to "Manual connection selected",
    "Ручное подключение удалено" to "Manual connection deleted",
    "Не удалось сохранить подключение" to "Could not save the connection",
    "Проверьте параметры подключения" to "Check the connection settings",
    "Выберите Moonraker или OctoPrint" to "Select Moonraker or OctoPrint",
    "Порт должен быть от 1 до 65535" to "Port must be between 1 and 65535",
    "Для Basic Auth нужны и логин, и пароль" to "Basic Auth requires both username and password",
    "Поля подключения не должны содержать переносы строк" to "Connection fields must not contain line breaks",
    "Укажите IP-адрес или имя принтера" to "Enter the printer IP address or host name",
    "В адресе принтера не должно быть логина, параметров или фрагмента" to
        "The printer address must not contain credentials, query parameters, or a fragment",
    "Укажите адрес сервера без пути" to "Enter the server address without a path",
    "Хранение профилей" to "Profile storage",
    "Профили OrcaCloud сохраняются на устройстве и доступны без интернета." to "OrcaCloud profiles are stored on the device and remain available offline.",
    "Приложение только читает данные OrcaCloud и ничего не изменяет в облаке." to "The app only reads OrcaCloud data and does not change anything in the cloud.",
    "Каталог принтеров OrcaSlicer" to "OrcaSlicer printer catalog",
    "Не удалось открыть встроенный каталог." to "Could not open the bundled catalog.",
    "Производитель или модель" to "Manufacturer or model",
    "Например, Kingroon KP3S" to "For example, Kingroon KP3S",
    "Профили не найдены" to "No profiles found",
    "Профили OrcaCloud" to "OrcaCloud profiles",
    "Загрузка профилей…" to "Loading profiles…",
    "Обновление профилей…" to "Refreshing profiles…",
    "Изменить ›" to "Change ›",
    "Диаметр сопла, мм" to "Nozzle diameter, mm",
    "Диаметр, мм" to "Diameter, mm",
    "Сопло, °C" to "Nozzle, °C",
    "Температура стола, °C" to "Bed temperature, °C",

    // Printing and result dialogs.
    "Печать запущена" to "Print started",
    "G-code загружен" to "G-code uploaded",
    "Файл загружен, печать не запущена" to "File uploaded, print not started",
    "Не удалось отправить" to "Send failed",
    "Ошибка соединения с принтером" to "Printer connection error",
    "Отправить и начать" to "Upload and start",
    "Загрузить и начать" to "Upload and start",
    "Только загрузить" to "Upload only",
    "Проверяем состояние принтера…" to "Checking printer status…",
    "Можно только загрузить G-code либо загрузить и сразу начать печать. Запуск доступен только после свежей проверки готовности принтера." to
        "You can upload the G-code only, or upload and start immediately. Starting is available only after a fresh printer readiness check.",
    "Открыть раздел «Принтер»" to "Open Printer section",
    "Отмена" to "Cancel",
    "Отправить на печать?" to "Send to printer?",
    "G-code будет загружен, после чего печать начнётся сразу. Проверьте выбранные профили и убедитесь, что принтер готов." to
        "The G-code will be uploaded and printing will start immediately. Check the selected profiles and make sure the printer is ready.",
    "G-code готов, но в активном профиле нет поддерживаемого адреса сетевого принтера. Выберите профиль OrcaCloud с Moonraker или OctoPrint." to
        "The G-code is ready, but the active profile has no supported network printer address. Select an OrcaCloud profile with Moonraker or OctoPrint.",
    "Отправка…" to "Sending…",
    "G-code готов" to "G-code ready",
    "Нарезано движком OrcaSlicer" to "Sliced with the OrcaSlicer engine",
    "Экспериментальный режим печатает только периметры. Проверьте G-code перед печатью." to "Experimental mode prints perimeters only. Check the G-code before printing.",

    // Toolpath preview.
    "Ширина линии" to "Line width",
    "Тип линии" to "Line type",
    "Скорость" to "Speed",
    "Высота слоя" to "Layer height",
    "Высота первого слоя" to "First layer height",
    "Просмотр нарезки" to "Sliced preview",
    "Окраска траектории" to "Toolpath coloring",
    "Нижний видимый слой" to "Lowest visible layer",
    "Верхний видимый слой" to "Highest visible layer",
    "Экструзия" to "Extrusion",
    "Перемещения" to "Travel moves",
    "Расчётное время" to "Estimated time",
    "Пруток" to "Filament",
    "Траектория печати" to "Print path",
    "Сегменты" to "Segments",
    "Скрыть команды G-code" to "Hide G-code commands",
    "Показать команды G-code" to "Show G-code commands",
    "Нет видимых команд" to "No visible commands",
    "Стены, оболочки, заполнение и поддержки построены движком OrcaSlicer согласно текущему профилю." to
        "Walls, shells, infill and supports were generated by the OrcaSlicer engine using the current profile.",

    // Print-settings editor.
    "Основные" to "Basic",
    "Расширенные" to "Advanced",
    "Экспертные" to "Expert",
    "Прочность" to "Strength",
    "Поддержки" to "Supports",
    "Многоцвет" to "Multimaterial",
    "Прочее" to "Other",
    "Профиль" to "Profile",
    "Настройки" to "Settings",
    "✓ Используется текущим ядром нарезки" to "✓ Used by the current slicing core",
    "Ширина линии по умолчанию" to "Default line width",
    "Первый слой" to "First layer",
    "Внешняя стенка" to "Outer wall",
    "Шов" to "Seam",
    "Положение шва" to "Seam position",
    "Смещать внутренние швы" to "Stagger inner seams",
    "Зазор шва" to "Seam gap",
    "Точность" to "Precision",
    "Разрешение" to "Resolution",
    "Точная внешняя стенка" to "Precise outer wall",
    "Аппроксимация дугами" to "Arc fitting",
    "Компенсация отверстий X/Y" to "X/Y hole compensation",
    "Компенсация слоновьей ноги" to "Elephant foot compensation",
    "Генератор стенок" to "Wall generator",
    "Генератор" to "Generator",
    "Порядок стенок" to "Wall order",
    "Сначала заполнение" to "Infill first",
    "Одна стенка сверху" to "One wall on top",
    "Стенки" to "Walls",
    "Количество контуров" to "Wall loops",
    "Чередовать дополнительную стенку" to "Alternate extra wall",
    "Определять тонкие стенки" to "Detect thin walls",
    "Мосты и нависания" to "Bridges and overhangs",
    "Определять нависающие стенки" to "Detect overhanging walls",
    "Коэффициент потока мостов" to "Bridge flow ratio",
    "Верхние и нижние оболочки" to "Top and bottom shells",
    "Верхних слоёв" to "Top shell layers",
    "Нижних слоёв" to "Bottom shell layers",
    "Рисунок верхней поверхности" to "Top surface pattern",
    "Рисунок нижней поверхности" to "Bottom surface pattern",
    "Заполнение" to "Infill",
    "Плотность заполнения" to "Infill density",
    "Рисунок заполнения" to "Infill pattern",
    "Направление" to "Direction",
    "Перекрытие со стенкой" to "Wall overlap",
    "Включить поддержки" to "Enable supports",
    "Включены" to "Enabled",
    "Выключены" to "Disabled",
    "Включена" to "Enabled",
    "Выключена" to "Disabled",
    "Тип" to "Type",
    "Порог нависания" to "Overhang threshold",
    "Только от стола" to "Build plate only",
    "Плот и интерфейс" to "Raft and interface",
    "Слоёв плота" to "Raft layers",
    "Верхний Z-зазор" to "Top Z distance",
    "Нижний Z-зазор" to "Bottom Z distance",
    "Верхних интерфейсных слоёв" to "Top interface layers",
    "Нижних интерфейсных слоёв" to "Bottom interface layers",
    "Шаг интерфейса" to "Interface spacing",
    "Древовидные поддержки" to "Tree supports",
    "Диаметр вершины" to "Tip diameter",
    "Расстояние между ветвями" to "Branch distance",
    "Угол ветвей" to "Branch angle",
    "Башня очистки" to "Prime tower",
    "Включить башню очистки" to "Enable prime tower",
    "Ширина" to "Width",
    "Объём очистки" to "Prime volume",
    "Ширина каймы" to "Brim width",
    "Очистка в модель" to "Flush into model",
    "Очищать в заполнение" to "Flush into infill",
    "Очищать в поддержки" to "Flush into supports",
    "Филамент элементов" to "Feature filament",
    "Внешние стенки" to "Outer walls",
    "Предотвращение подтекания" to "Ooze prevention",
    "Включить" to "Enable",
    "Изменение температуры ожидания" to "Standby temperature delta",
    "Юбка" to "Skirt",
    "Контуров" to "Loops",
    "Расстояние от модели" to "Distance from model",
    "Минимальная длина экструзии" to "Minimum extrusion length",
    "Кайма" to "Brim",
    "Тип каймы" to "Brim type",
    "Зазор до модели" to "Object gap",
    "Базовая скорость" to "Base speed",
    "Внутренняя стенка" to "Inner wall",
    "Ускорение" to "Acceleration",
    "Специальный режим" to "Special mode",
    "Режим нарезки" to "Slicing mode",
    "Последовательность печати" to "Print sequence",
    "Спиральная ваза" to "Spiral vase",
    "Пушистая поверхность" to "Fuzzy skin",
    "Вывод G-code" to "G-code output",
    "Подробные комментарии" to "Detailed comments",
    "Метки объектов" to "Object labels",
    "Поддержка исключения объектов" to "Object exclusion support",
    "Шаблон имени файла" to "Filename template",
    "мм" to "mm",
    "мм/с" to "mm/s",
    "мм/с²" to "mm/s²",
    "мм³" to "mm³",

    // Choice labels.
    "Ближайшая" to "Nearest",
    "Выровненная" to "Aligned",
    "Сзади" to "Back",
    "Случайная" to "Random",
    "Классический" to "Classic",
    "Внутренняя → внешняя" to "Inner → outer",
    "Внешняя → внутренняя" to "Outer → inner",
    "Внутренняя → внешняя → внутренняя" to "Inner → outer → inner",
    "Монотонные линии" to "Monotonic lines",
    "Монотонный" to "Monotonic",
    "Линии" to "Lines",
    "Концентрический" to "Concentric",
    "Гироид" to "Gyroid",
    "Сетка" to "Grid",
    "Соты" to "Honeycomb",
    "Кубический" to "Cubic",
    "Адаптивный кубический" to "Adaptive cubic",
    "Обычная (авто)" to "Normal (auto)",
    "Обычная (ручная)" to "Normal (manual)",
    "Дерево (авто)" to "Tree (auto)",
    "Дерево (ручная)" to "Tree (manual)",
    "Без каймы" to "No brim",
    "Автоматическая" to "Automatic",
    "Только внешняя" to "Outer only",
    "Только внутренняя" to "Inner only",
    "Внешняя и внутренняя" to "Outer and inner",
    "Обычный" to "Regular",
    "Чётно-нечётный" to "Even-odd",
    "Закрывать отверстия" to "Close holes",
    "По слоям" to "By layer",
    "По объектам" to "By object",

    // Errors and technical status.
    "Не удалось импортировать выбранный файл" to "Could not import the selected file",
    "Не удалось открыть выбранную папку" to "Could not open the selected folder",
    "Не удалось сохранить G-code" to "Could not save G-code",
    "Проверьте числовые параметры печати" to "Check the numeric print settings",
    "Ошибка слайсера" to "Slicer error",
    "Неподдерживаемый раздел профиля" to "Unsupported profile section",
    "Не удалось подключиться к принтеру" to "Could not connect to the printer",
    "Принтер не ответил вовремя" to "The printer did not respond in time",
    "Принтер отклонил авторизацию" to "The printer rejected authentication",
    "Сервер принтера вернул пустой ответ" to "The printer server returned an empty response",
    "Сервер принтера вернул некорректный JSON" to "The printer server returned invalid JSON",
    "Ответ сервера принтера слишком большой" to "The printer server response is too large",
    "Некорректный адрес или порт принтера" to "Invalid printer address or port",
    "Подключение к PrusaLink пока не поддерживается" to "PrusaLink connection is not supported yet",
    "Текущая версия поддерживает только файлы STL" to "The current version supports STL files only",
    "Поддерживаются только модели STL, OBJ и 3MF" to "Only STL, OBJ, and 3MF models are supported",
    "Не удалось положить модель гранью" to "Could not lay the model flat",
    "Не удалось найти подходящую грань" to "Could not find a suitable face",
    "Не удалось переименовать модель" to "Could not rename the model",
    "Не удалось прочитать выбранный документ" to "Could not read the selected document",
    "Сервер ответил, но это не похоже на Moonraker" to "The server responded, but it does not appear to be Moonraker",
    "Отправка в PrusaLink пока не поддерживается" to "Sending to PrusaLink is not supported yet",
    "Неизвестный тип сервера печати" to "Unknown print server type",
    "G-code файл не найден" to "G-code file not found",
    "Этот протокол отправки пока не поддерживается" to "This upload protocol is not supported yet",
    "Поддерживаются только HTTP и HTTPS" to "Only HTTP and HTTPS are supported",
    "Некорректный адрес принтера" to "Invalid printer address",
    "Некорректный порт принтера" to "Invalid printer port",
    "Неизвестный протокол" to "Unknown protocol",
)

private val ENGLISH_REPLACEMENTS: List<Pair<String, String>> = buildList {
    addAll(ENGLISH_TEXT.entries.map { it.key to it.value })
    addAll(
        listOf(
            "Модель находится в пределах стола" to "Model is within the print bed",
            "Границы" to "Bounds",
            " · В " to " · H ",
            "Размер:" to "Size:",
            "Принтеры:" to "Printers:",
            "филаменты:" to "filaments:",
            "печать:" to "print:",
            "производителя" to "manufacturers",
            "профилей" to "profiles",
            "доступно офлайн" to "available offline",
            "Найдено:" to "Found:",
            "показаны первые" to "showing the first",
            "Ещё профилей:" to "More profiles:",
            "Завершите вход через" to "Complete sign-in with",
            "в браузере." to "in the browser.",
            "Адрес:" to "Address:",
            "Источник:" to "Source:",
            "Состояние:" to "Status:",
            "Предупреждение:" to "Warning:",
            "Задание:" to "Job:",
            "Печать:" to "Print:",
            "Сопло " to "Nozzle ",
            "Стол " to "Bed ",
            "в сети" to "online",
            "не готов" to "not ready",
            "готов" to "ready",
            "печатает" to "printing",
            "пауза" to "paused",
            "запускается" to "starting",
            "неизвестно" to "unknown",
            "ожидание" to "idle",
            "идёт" to "in progress",
            "приостановлена" to "paused",
            "завершена" to "complete",
            "отменена" to "cancelled",
            "Печать не запускалась." to "Printing was not started.",
            "сохранён на принтере." to "was saved on the printer.",
            "Протокол:" to "Protocol:",
            "Порт:" to "Port:",
            "Область печати:" to "Build volume:",
            "Формат G-code:" to "G-code flavor:",
            "локальный кэш" to "local cache",
            "локальный demo" to "local demo",
            "загружены из облака" to "loaded from the cloud",
            "Профилей:" to "Profiles:",
            "Объектов:" to "Objects:",
            "Треугольников:" to "Triangles:",
            "Добавлено моделей:" to "Models added:",
            "Пересечение габаритов с другими моделями:" to "Bounding-box overlaps with other models:",
            "Не поместилось моделей:" to "Models that did not fit:",
            "Показать все" to "Show all",
            "Ход траектории" to "Toolpath move",
            "Слои" to "Layers",
            " из " to " of ",
            "слоёв" to "layers",
            "Слоёв:" to "Layers:",
            "сегментов" to "segments",
            "Сегментов экструзии:" to "Extrusion segments:",
            "Прочитано" to "Read",
            "строк G-code" to "G-code lines",
            "Расчётный расход филамента:" to "Estimated filament use:",
            "Нижний" to "Lower",
            "Верхний" to "Upper",
            "Скорость" to "Speed",
            "Ширина" to "Width",
            "Печать запущена" to "Print started",
            "файл" to "file",
            "загружен, команда печати отправлена." to "uploaded; the print command was sent.",
            "Принтер отклонил запрос:" to "The printer rejected the request:",
            "Сервер принтера вернул HTTP" to "The printer server returned HTTP",
            "Moonraker доступен" to "Moonraker available",
            "доступен" to "available",
            "контур" to "loop",
            "контура" to "loops",
            "МБ" to "MB",
            "КБ" to "KB",
            " Б" to " B",
        ),
    )
}.sortedByDescending { it.first.length }
