// SPDX-License-Identifier: AGPL-3.0-only
package tech.g24.feresaslicer.ui

import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.Text as MaterialText
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit
import java.util.Locale

enum class UiLanguage {
    RUSSIAN,
    ENGLISH,
}

fun resolveUiLanguage(locale: Locale): UiLanguage =
    if (locale.language.equals("ru", ignoreCase = true)) UiLanguage.RUSSIAN else UiLanguage.ENGLISH

@Composable
fun currentUiLanguage(): UiLanguage {
    val locales = LocalConfiguration.current.locales
    val locale = if (locales.isEmpty) Locale.getDefault() else locales[0]
    return resolveUiLanguage(locale)
}

/**
 * Localized Material 3 text used throughout the app.
 *
 * The project originally shipped with Russian literals embedded in Compose code. Keeping this
 * compatibility layer lets every existing screen participate in locale changes while translations
 * are centralized and testable. Russian is retained for Russian devices; English is the fallback
 * for every other system locale.
 */
@Composable
fun Text(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: (TextLayoutResult) -> Unit = {},
    style: TextStyle = LocalTextStyle.current,
) {
    MaterialText(
        text = localizeUiText(text, currentUiLanguage()),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style,
    )
}

fun localizeUiText(text: String, language: UiLanguage): String {
    if (language == UiLanguage.RUSSIAN || text.none { it in '\u0400'..'\u04FF' }) return text
    ENGLISH_TEXT[text]?.let { return it }

    var translated = text
    ENGLISH_REPLACEMENTS.forEach { (russian, english) ->
        translated = translated.replace(russian, english)
    }
    return translated
}

private val ENGLISH_TEXT = mapOf(
    // Application shell and model workspace.
    "Системная" to "System",
    "Светлая" to "Light",
    "Тёмная" to "Dark",
    "Модель" to "Model",
    "Модель и печатный стол" to "Model and print bed",
    "Принтер" to "Printer",
    "Профиль принтера" to "Printer profile",
    "Филамент" to "Filament",
    "Профиль материала" to "Material profile",
    "Печать" to "Print",
    "Параметры печати" to "Print settings",
    "Приложение" to "App",
    "Настройки и синхронизация" to "Settings and synchronization",
    "Меню" to "Menu",
    "Файл" to "File",
    "Вид" to "View",
    "Положение" to "Position",
    "Нарезка" to "Slice",
    "Файл модели" to "Model file",
    "Файл не выбран" to "No file selected",
    "Поддерживаются модели STL в binary- и ASCII-формате." to "Binary and ASCII STL models are supported.",
    "Формат: STL" to "Format: STL",
    "Состояние: нарезка готова" to "Status: slicing complete",
    "Состояние: модель загружена" to "Status: model loaded",
    "Загрузить STL" to "Load STL",
    "Заменить STL" to "Replace STL",
    "Удалить файл" to "Remove file",
    "Расположение модели" to "Model placement",
    "Создание 3D-модели по фото пока недоступно" to "Creating a 3D model from a photo is not available yet",
    "Экспорт профилей будет добавлен в следующей версии" to "Profile export will be added in a future version",
    "Модель выходит за пределы печатного стола" to "The model extends beyond the print bed",
    "Позиция X" to "X position",
    "Позиция Y" to "Y position",
    "Поворот" to "Rotation",
    "Масштаб" to "Scale",
    "По центру" to "Center",
    "Повернуть 90°" to "Rotate 90°",
    "Модели" to "Models",
    "Удалить" to "Remove",
    "Из фото" to "From photo",
    "Калибр." to "Calibrate",
    "Импорт проф." to "Import profiles",
    "Экспорт проф." to "Export profiles",
    "Общий вид" to "Overview",
    "Траектория" to "Toolpath",
    "Масштаб 1:1" to "Scale 1:1",
    "Нарезать" to "Slice",
    "На печать" to "Send to printer",
    "Сохранить" to "Save",
    "НАРЕЗАТЬ МОДЕЛЬ" to "SLICE MODEL",
    "Нарезка…" to "Slicing…",
    "Выберите STL во вкладке «Файл», затем вернитесь сюда для нарезки." to "Select an STL on the File tab, then return here to slice it.",
    "Модель готова. После нарезки здесь появится послойная траектория G-code." to "The model is ready. A layer-by-layer G-code toolpath will appear here after slicing.",

    // App settings, accounts, and dialogs.
    "Настройки приложения" to "App settings",
    "Язык интерфейса" to "Interface language",
    "Русский" to "English",
    "Тема" to "Theme",
    "Локальный слайсер" to "Local slicer",
    "Включён и всегда доступен без интернета" to "Enabled and always available offline",
    "Локальный слайсер бесплатный" to "Local slicing is free",
    "Синхронизация профилей будет доступна по подписке." to "Profile synchronization will be available with a subscription.",
    "Синхронизация профилей" to "Profile synchronization",
    "Загружено из OrcaCloud" to "Loaded from OrcaCloud",
    "Подключение загружено из OrcaCloud" to "Connection loaded from OrcaCloud",
    "Показаны данные из локального кэша" to "Showing locally cached data",
    "После входа здесь появятся ваши профили OrcaCloud." to "Your OrcaCloud profiles will appear here after you sign in.",
    "Синхронизация…" to "Synchronizing…",
    "Обновить профили" to "Refresh profiles",
    "Только чтение: приложение загружает профили, но не изменяет данные OrcaCloud." to "Read-only: the app downloads profiles but does not modify OrcaCloud data.",
    "AGPL-3.0 · Лицензия и исходный код" to "AGPL-3.0 · License and source code",
    "Закрыть" to "Close",
    "Свободное программное обеспечение" to "Free and open-source software",
    "Feresa Slicer распространяется по лицензии GNU AGPL версии 3. Исходный код, сценарии сборки, уведомления и текст лицензии включены в проект. Программа предоставляется без гарантий." to
        "Feresa Slicer is distributed under the GNU AGPL version 3. The source code, build scripts, notices, and license text are included in the project. The software is provided without warranty.",
    "Учётная запись OrcaCloud" to "OrcaCloud account",
    "Проверка сохранённой сессии…" to "Checking saved session…",
    "Безопасный вход откроется в браузере. Приложение не получает ваш пароль." to "Secure sign-in opens in your browser. The app never receives your password.",
    "Отменить вход" to "Cancel sign-in",
    "Выйти" to "Sign out",
    "Повторить" to "Retry",
    "Войти" to "Sign in",
    "Открыть меню приложения" to "Open app menu",
    "Обновить из OrcaCloud" to "Refresh from OrcaCloud",
    "Обновление…" to "Refreshing…",
    "В OrcaCloud нет пользовательских профилей этого типа." to "There are no custom profiles of this type in OrcaCloud.",
    "Войдите в OrcaCloud, чтобы загрузить свои профили." to "Sign in to OrcaCloud to load your profiles.",
    "Профили пока не загружены" to "Profiles have not been loaded yet",
    "Войти в OrcaCloud" to "Sign in to OrcaCloud",
    "Выбран" to "Selected",
    "Выбрать" to "Select",
    "Активен" to "Active",
    "Подключён" to "Connected",
    "Используется для подключения" to "Used for connection",

    // Printer, profiles, and catalog.
    "Подключение к принтеру" to "Printer connection",
    "Авторизация настроена" to "Authentication configured",
    "Без API-ключа" to "No API key",
    "Проверка…" to "Checking…",
    "Проверить подключение" to "Test connection",
    "Принтер не подключён" to "Printer not connected",
    "Выберите профиль OrcaCloud, содержащий print_host и host_type." to "Select an OrcaCloud profile containing print_host and host_type.",
    "Хранение профилей" to "Profile storage",
    "Профили OrcaCloud сохраняются на устройстве и доступны без интернета." to "OrcaCloud profiles are stored on the device and remain available offline.",
    "Приложение только читает данные OrcaCloud и ничего не изменяет в облаке." to "The app only reads OrcaCloud data and does not change anything in the cloud.",
    "Каталог принтеров OrcaSlicer" to "OrcaSlicer printer catalog",
    "Не удалось открыть встроенный каталог." to "Could not open the bundled catalog.",
    "Производитель или модель" to "Manufacturer or model",
    "Например, Kingroon KP3S" to "For example, Kingroon KP3S",
    "Профили не найдены" to "No profiles found",
    "Профили OrcaCloud" to "OrcaCloud profiles",
    "Загрузка профилей…" to "Loading profiles…",
    "Обновление профилей…" to "Refreshing profiles…",
    "Изменить ›" to "Change ›",
    "Диаметр сопла, мм" to "Nozzle diameter, mm",
    "Диаметр, мм" to "Diameter, mm",
    "Сопло, °C" to "Nozzle, °C",
    "Температура стола, °C" to "Bed temperature, °C",

    // Printing and result dialogs.
    "Печать запущена" to "Print started",
    "Не удалось отправить" to "Send failed",
    "Ошибка соединения с принтером" to "Printer connection error",
    "Отправить и начать" to "Upload and start",
    "Открыть раздел «Принтер»" to "Open Printer section",
    "Отмена" to "Cancel",
    "Отправить на печать?" to "Send to printer?",
    "G-code будет загружен, после чего печать начнётся сразу. Текущий слайсер экспериментальный — убедитесь, что принтер готов." to
        "The G-code will be uploaded and printing will start immediately. The current slicer is experimental—make sure the printer is ready.",
    "G-code готов, но в активном профиле нет поддерживаемого адреса сетевого принтера. Выберите профиль OrcaCloud с Moonraker или OctoPrint." to
        "The G-code is ready, but the active profile has no supported network printer address. Select an OrcaCloud profile with Moonraker or OctoPrint.",
    "Отправка…" to "Sending…",
    "G-code готов" to "G-code ready",
    "Экспериментальный режим печатает только периметры. Проверьте G-code перед печатью." to "Experimental mode prints perimeters only. Check the G-code before printing.",

    // Toolpath preview.
    "Ширина линии" to "Line width",
    "Тип линии" to "Line type",
    "Скорость" to "Speed",
    "Высота слоя" to "Layer height",
    "Высота первого слоя" to "First layer height",
    "Просмотр нарезки" to "Sliced preview",
    "Окраска траектории" to "Toolpath coloring",
    "Нижний видимый слой" to "Lowest visible layer",
    "Верхний видимый слой" to "Highest visible layer",
    "Внешние периметры" to "Outer perimeters",
    "Перемещения" to "Travel moves",
    "Расчётное время" to "Estimated time",
    "Пруток" to "Filament",
    "Траектория печати" to "Print path",
    "Сегменты" to "Segments",
    "Скрыть команды G-code" to "Hide G-code commands",
    "Показать команды G-code" to "Show G-code commands",
    "Нет видимых команд" to "No visible commands",
    "Сейчас мобильное ядро строит внешние периметры. Заполнение и поддержки появятся после подключения полного ядра OrcaSlicer." to
        "The mobile core currently generates outer perimeters. Infill and supports will be available after the full OrcaSlicer core is integrated.",

    // Print-settings editor.
    "Основные" to "Basic",
    "Расширенные" to "Advanced",
    "Экспертные" to "Expert",
    "Прочность" to "Strength",
    "Поддержки" to "Supports",
    "Многоцвет" to "Multimaterial",
    "Прочее" to "Other",
    "Профиль" to "Profile",
    "Настройки" to "Settings",
    "✓ Используется текущим ядром нарезки" to "✓ Used by the current slicing core",
    "Ширина линии по умолчанию" to "Default line width",
    "Первый слой" to "First layer",
    "Внешняя стенка" to "Outer wall",
    "Шов" to "Seam",
    "Положение шва" to "Seam position",
    "Смещать внутренние швы" to "Stagger inner seams",
    "Зазор шва" to "Seam gap",
    "Точность" to "Precision",
    "Разрешение" to "Resolution",
    "Точная внешняя стенка" to "Precise outer wall",
    "Аппроксимация дугами" to "Arc fitting",
    "Компенсация отверстий X/Y" to "X/Y hole compensation",
    "Компенсация слоновьей ноги" to "Elephant foot compensation",
    "Генератор стенок" to "Wall generator",
    "Генератор" to "Generator",
    "Порядок стенок" to "Wall order",
    "Сначала заполнение" to "Infill first",
    "Одна стенка сверху" to "One wall on top",
    "Стенки" to "Walls",
    "Количество контуров" to "Wall loops",
    "Чередовать дополнительную стенку" to "Alternate extra wall",
    "Определять тонкие стенки" to "Detect thin walls",
    "Мосты и нависания" to "Bridges and overhangs",
    "Определять нависающие стенки" to "Detect overhanging walls",
    "Коэффициент потока мостов" to "Bridge flow ratio",
    "Верхние и нижние оболочки" to "Top and bottom shells",
    "Верхних слоёв" to "Top shell layers",
    "Нижних слоёв" to "Bottom shell layers",
    "Рисунок верхней поверхности" to "Top surface pattern",
    "Рисунок нижней поверхности" to "Bottom surface pattern",
    "Заполнение" to "Infill",
    "Плотность заполнения" to "Infill density",
    "Рисунок заполнения" to "Infill pattern",
    "Направление" to "Direction",
    "Перекрытие со стенкой" to "Wall overlap",
    "Включить поддержки" to "Enable supports",
    "Включены" to "Enabled",
    "Выключены" to "Disabled",
    "Включена" to "Enabled",
    "Выключена" to "Disabled",
    "Тип" to "Type",
    "Порог нависания" to "Overhang threshold",
    "Только от стола" to "Build plate only",
    "Плот и интерфейс" to "Raft and interface",
    "Слоёв плота" to "Raft layers",
    "Верхний Z-зазор" to "Top Z distance",
    "Нижний Z-зазор" to "Bottom Z distance",
    "Верхних интерфейсных слоёв" to "Top interface layers",
    "Нижних интерфейсных слоёв" to "Bottom interface layers",
    "Шаг интерфейса" to "Interface spacing",
    "Древовидные поддержки" to "Tree supports",
    "Диаметр вершины" to "Tip diameter",
    "Расстояние между ветвями" to "Branch distance",
    "Угол ветвей" to "Branch angle",
    "Башня очистки" to "Prime tower",
    "Включить башню очистки" to "Enable prime tower",
    "Ширина" to "Width",
    "Объём очистки" to "Prime volume",
    "Ширина каймы" to "Brim width",
    "Очистка в модель" to "Flush into model",
    "Очищать в заполнение" to "Flush into infill",
    "Очищать в поддержки" to "Flush into supports",
    "Филамент элементов" to "Feature filament",
    "Внешние стенки" to "Outer walls",
    "Предотвращение подтекания" to "Ooze prevention",
    "Включить" to "Enable",
    "Изменение температуры ожидания" to "Standby temperature delta",
    "Юбка" to "Skirt",
    "Контуров" to "Loops",
    "Расстояние от модели" to "Distance from model",
    "Минимальная длина экструзии" to "Minimum extrusion length",
    "Кайма" to "Brim",
    "Тип каймы" to "Brim type",
    "Зазор до модели" to "Object gap",
    "Базовая скорость" to "Base speed",
    "Внутренняя стенка" to "Inner wall",
    "Ускорение" to "Acceleration",
    "Специальный режим" to "Special mode",
    "Режим нарезки" to "Slicing mode",
    "Последовательность печати" to "Print sequence",
    "Спиральная ваза" to "Spiral vase",
    "Пушистая поверхность" to "Fuzzy skin",
    "Вывод G-code" to "G-code output",
    "Подробные комментарии" to "Detailed comments",
    "Метки объектов" to "Object labels",
    "Поддержка исключения объектов" to "Object exclusion support",
    "Шаблон имени файла" to "Filename template",
    "мм" to "mm",
    "мм/с" to "mm/s",
    "мм/с²" to "mm/s²",
    "мм³" to "mm³",

    // Choice labels.
    "Ближайшая" to "Nearest",
    "Выровненная" to "Aligned",
    "Сзади" to "Back",
    "Случайная" to "Random",
    "Классический" to "Classic",
    "Внутренняя → внешняя" to "Inner → outer",
    "Внешняя → внутренняя" to "Outer → inner",
    "Внутренняя → внешняя → внутренняя" to "Inner → outer → inner",
    "Монотонные линии" to "Monotonic lines",
    "Монотонный" to "Monotonic",
    "Линии" to "Lines",
    "Концентрический" to "Concentric",
    "Гироид" to "Gyroid",
    "Сетка" to "Grid",
    "Соты" to "Honeycomb",
    "Кубический" to "Cubic",
    "Адаптивный кубический" to "Adaptive cubic",
    "Обычная (авто)" to "Normal (auto)",
    "Обычная (ручная)" to "Normal (manual)",
    "Дерево (авто)" to "Tree (auto)",
    "Дерево (ручная)" to "Tree (manual)",
    "Без каймы" to "No brim",
    "Автоматическая" to "Automatic",
    "Только внешняя" to "Outer only",
    "Только внутренняя" to "Inner only",
    "Внешняя и внутренняя" to "Outer and inner",
    "Обычный" to "Regular",
    "Чётно-нечётный" to "Even-odd",
    "Закрывать отверстия" to "Close holes",
    "По слоям" to "By layer",
    "По объектам" to "By object",

    // Errors and technical status.
    "Не удалось импортировать выбранный файл" to "Could not import the selected file",
    "Не удалось открыть выбранную папку" to "Could not open the selected folder",
    "Не удалось сохранить G-code" to "Could not save G-code",
    "Проверьте числовые параметры печати" to "Check the numeric print settings",
    "Ошибка слайсера" to "Slicer error",
    "Неподдерживаемый раздел профиля" to "Unsupported profile section",
    "Не удалось подключиться к принтеру" to "Could not connect to the printer",
    "Текущая версия поддерживает только файлы STL" to "The current version supports STL files only",
    "Не удалось прочитать выбранный документ" to "Could not read the selected document",
    "Сервер ответил, но это не похоже на Moonraker" to "The server responded, but it does not appear to be Moonraker",
    "Отправка в PrusaLink пока не поддерживается" to "Sending to PrusaLink is not supported yet",
    "Неизвестный тип сервера печати" to "Unknown print server type",
    "G-code файл не найден" to "G-code file not found",
    "Этот протокол отправки пока не поддерживается" to "This upload protocol is not supported yet",
    "Поддерживаются только HTTP и HTTPS" to "Only HTTP and HTTPS are supported",
    "Некорректный адрес принтера" to "Invalid printer address",
    "Некорректный порт принтера" to "Invalid printer port",
    "Неизвестный протокол" to "Unknown protocol",
)

private val ENGLISH_REPLACEMENTS: List<Pair<String, String>> = buildList {
    addAll(ENGLISH_TEXT.entries.sortedByDescending { it.key.length }.map { it.key to it.value })
    addAll(
        listOf(
            "Модель находится в пределах стола" to "Model is within the print bed",
            "Границы" to "Bounds",
            "Размер:" to "Size:",
            "Принтеры:" to "Printers:",
            "филаменты:" to "filaments:",
            "печать:" to "print:",
            "производителя" to "manufacturers",
            "профилей" to "profiles",
            "доступно офлайн" to "available offline",
            "Найдено:" to "Found:",
            "показаны первые" to "showing the first",
            "Ещё профилей:" to "More profiles:",
            "Завершите вход через" to "Complete sign-in with",
            "в браузере." to "in the browser.",
            "Адрес:" to "Address:",
            "Протокол:" to "Protocol:",
            "Порт:" to "Port:",
            "Область печати:" to "Build volume:",
            "Формат G-code:" to "G-code flavor:",
            "локальный кэш" to "local cache",
            "загружены из облака" to "loaded from the cloud",
            "Профилей:" to "Profiles:",
            "Ход траектории" to "Toolpath move",
            "Слои" to "Layers",
            " из " to " of ",
            "слоёв" to "layers",
            "Слоёв:" to "Layers:",
            "сегментов" to "segments",
            "Сегментов экструзии:" to "Extrusion segments:",
            "Прочитано" to "Read",
            "строк G-code" to "G-code lines",
            "Расчётный расход филамента:" to "Estimated filament use:",
            "Нижний" to "Lower",
            "Верхний" to "Upper",
            "Скорость" to "Speed",
            "Ширина" to "Width",
            "Печать запущена" to "Print started",
            "файл" to "file",
            "загружен, команда печати отправлена." to "uploaded; the print command was sent.",
            "Принтер отклонил запрос:" to "The printer rejected the request:",
            "Moonraker доступен" to "Moonraker available",
            "доступен" to "available",
            "контур" to "loop",
            "контура" to "loops",
            "МБ" to "MB",
            "КБ" to "KB",
            " Б" to " B",
        ),
    )
}
